# Generated by Django 5.2.3 on 2025-06-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='lalitude',
            new_name='latitude',
        ),
    ]
